# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_tone_from_voice', '0003_auto_20171105_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADHD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PTSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
